/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JOptionPane;
import Figuras.Cilindro;
import Figuras.Circulo;
import Figuras.Cuadrado;
import Figuras.Cubo;
import Figuras.PiramideBaseCuadrada;
import Figuras.Rectangulo;
import Figuras.Trapecio;
import Figuras.Triangulo;
import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author janeth
 */
public class VentanaFiguras extends javax.swing.JInternalFrame {

    DecimalFormat df = new DecimalFormat("#.0000");
    ImageIcon imagen = new ImageIcon("src/Presentacion/Trapecio.JPG");
    //Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_DEFAULT));

    /**
     * Creates new form VentanaFiguras
     */
    public VentanaFiguras() {
        initComponents();
        jComboBox1.addItem("Cilindro");
        jComboBox1.addItem("Cuadrado");
        jComboBox1.addItem("Cubo");
        jComboBox1.addItem("Piramide de base cuadrada");
        jComboBox1.addItem("Rectangulo");
        jComboBox1.addItem("Trapecio");
        jComboBox1.addItem("Triangulo");
        jComboBox1.addItem("Circulo");
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Areas y Volumenes");
        setPreferredSize(new java.awt.Dimension(460, 400));

        jLabel1.setText("Elija una figura:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Resultado");

        jLabel7.setText("jLabel7");

        jLabel8.setText("Ingrese los datos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jButton1.setVisible(false);
        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "Escoja una figura");
                break;
            case 1:
                jButton1.setVisible(true);
                jButton1.setText("Calcular Volumen");
                jLabel2.setText("Altura:");
                jLabel3.setText("Radio:");
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jTextField1.setVisible(true);
                jTextField2.setVisible(true);
                break;
            case 2:
                jButton1.setVisible(true);
                jButton1.setText("Calcular Area");
                jLabel2.setText("Lado:");
                jLabel2.setVisible(true);
                jTextField1.setVisible(true);
                break;
            case 3:
                jButton1.setVisible(true);
                jButton1.setText("Calcular Volumen");
                jLabel2.setText("Altura:");
                jLabel2.setVisible(true);
                jTextField1.setVisible(true);
                break;
            case 4:
                jButton1.setVisible(true);
                jButton1.setText("Calcular Volumen");
                jLabel2.setText("Altura:");
                jLabel3.setText("Lado Base:");
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jTextField1.setVisible(true);
                jTextField2.setVisible(true);
                jButton1.setVisible(true);
                break;
            case 5:
                jButton1.setVisible(true);
                jButton1.setText("Calcular Area");
                jLabel2.setText("Largo:");
                jLabel3.setText("Ancho:");
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jTextField1.setVisible(true);
                jTextField2.setVisible(true);

                break;
            case 6:
                jButton1.setVisible(true);
                jButton1.setText("Calcular Area");
                jLabel2.setText("LadoA:");
                jLabel3.setText("LadoB:");
                jLabel4.setText("LadoC:");
                jLabel5.setText("LadoD:");
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
                jTextField1.setVisible(true);
                jTextField2.setVisible(true);
                jTextField3.setVisible(true);
                jTextField4.setVisible(true);

                break;
            case 7:
                jButton1.setVisible(true);
                jButton1.setText("Calcular Area");
                jLabel2.setText("LadoA:");
                jLabel3.setText("LadoB:");
                jLabel4.setText("LadoC:");
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jLabel4.setVisible(true);
                jTextField1.setVisible(true);
                jTextField2.setVisible(true);
                jTextField3.setVisible(true);
                break;
            case 8:
                jButton1.setVisible(true);
                jButton1.setText("Calcular Area");
                jLabel2.setText("Radio:");
                jLabel2.setVisible(true);
                jTextField1.setVisible(true);
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel6.setVisible(true);
        switch (jComboBox1.getSelectedIndex()) {
            case 1:
                Cilindro ObjCilindro = new Cilindro(Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()));
                jLabel6.setText("El volumen es: " + df.format(ObjCilindro.CalcularVolumenCilindro()));
                break;
            case 2:
                Cuadrado ObjCuadrado = new Cuadrado(Double.parseDouble(jTextField1.getText()));
                jLabel6.setText("El area es: " + df.format(ObjCuadrado.CalcularAreaCuadrado()));
                break;
            case 3:
                Cubo ObjCubo = new Cubo(Double.parseDouble(jTextField1.getText()));
                jLabel6.setText("El volumen es: " + df.format(ObjCubo.CalcularVolumenCubo()));
                break;
            case 4:
                PiramideBaseCuadrada ObjPiramide = new PiramideBaseCuadrada(Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()));
                jLabel6.setText("El volumen es: " + df.format(ObjPiramide.CalcularVolumenPiramideBC()));
                break;
            case 5:
                Rectangulo ObjRectangulo = new Rectangulo(Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()));
                jLabel6.setText("El area es: " + df.format(ObjRectangulo.CalcularAreaRectangulo()));
                break;
            case 6:
                Trapecio ObjTrapecio = new Trapecio(Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()), Double.parseDouble(jTextField3.getText()), Double.parseDouble(jTextField4.getText()));
                jLabel6.setText("El area es: " + df.format(ObjTrapecio.CalcularAreaTrapecio()));
                break;
            case 7:
                Triangulo ObjTriangulo = new Triangulo(Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()), Double.parseDouble(jTextField3.getText()));
                jLabel6.setText("El area es: " + df.format(ObjTriangulo.CalcularAreaTriangulo()));
                break;
            case 8:
                Circulo ObjCirculo = new Circulo(Double.parseDouble(jTextField1.getText()));
                jLabel6.setText("El area es: " + df.format(ObjCirculo.CalcularAreaCirculo()));
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
